services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8001:80"
    restart: always

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8002:8000"
    restart: always

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "8003:8000"
    restart: always

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8004:8000"
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always

volumes:
  grafana-data:
